### ISSUE TITLE
Post v1 cleanup

### ISSUE THREAD

**Issue by thokra-nav** [nais/api#65]
- [x] Database schema bør unngå å referere til app når det mener workload name (a74637800e5e0b00a8e31f1cef1a04c95387ddd1)
- [x] `cost_type` på `cost` tabellen renames til `service` (04ddb95470893ae23e781df92579963616f22919)
- [x] Endre fra Azure AD til Entra ID (2d05d80a4a3a341b71a8243c4bf6d48f1042a938)

**Comment by christeredvartsen** [comment]
Migration:

```sql
ALTER TABLE teams RENAME COLUMN azure_group_id TO entra_id_group_id;
```
